/**
 * Generates supabase/seed.sql from the canonical local seed (src/lib/seed.ts),
 * so the database and the local fallback never drift.
 *
 * Run:  npm run seed:sql
 * (Uses Node's native TypeScript type-stripping — Node 22.6+/24.)
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  categories,
  qualities,
  collections,
  designs,
  journal,
} from "../src/lib/seed.ts";

const q = (v: unknown): string => {
  if (v === undefined || v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const j = (v: unknown): string => (v == null ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`);
const arr = (v: string[] | undefined): string =>
  v && v.length ? `array[${v.map((s) => q(s)).join(",")}]` : "'{}'";

const out: string[] = [
  "-- Auto-generated by scripts/generate-seed-sql.ts — do not edit by hand.",
  "-- Mirrors src/lib/seed.ts. Run after schema.sql.",
  "",
];

for (const c of categories) {
  out.push(
    `insert into categories (id,name,slug,hero_image,description,seo,sort) values (${q(c.id)},${q(c.name)},${q(c.slug)},${q(c.heroImage)},${q(c.description)},${j(c.seo)},${c.sort}) on conflict (id) do nothing;`,
  );
}
out.push("");
for (const x of qualities) {
  out.push(
    `insert into qualities (id,name,code,slug,fabric_type,width,composition,foil,hero_image,category_id,seo) values (${q(x.id)},${q(x.name)},${q(x.code)},${q(x.slug)},${q(x.fabricType)},${q(x.width)},${q(x.composition)},${x.foil},${q(x.heroImage)},${q(x.categoryId)},${j(x.seo)}) on conflict (id) do nothing;`,
  );
}
out.push("");
for (const c of collections) {
  out.push(
    `insert into collections (id,title,slug,type,hero_image,description,status,seo) values (${q(c.id)},${q(c.title)},${q(c.slug)},${q(c.type)},${q(c.heroImage)},${q(c.description)},${q(c.status)},${j(c.seo)}) on conflict (id) do nothing;`,
  );
}
out.push("");
for (const d of designs) {
  out.push(
    `insert into designs (id,title,slug,design_no,category_id,quality_id,collection_id,images,description,status,seo) values (${q(d.id)},${q(d.title)},${q(d.slug)},${q(d.designNo)},${q(d.categoryId)},${q(d.qualityId)},${q(d.collectionId)},${j(d.images)},${q(d.description)},${q(d.status)},${j(d.seo)}) on conflict (id) do nothing;`,
  );
  out.push(
    `insert into collection_items (collection_id,design_id) values (${q(d.collectionId)},${q(d.id)}) on conflict do nothing;`,
  );
}
out.push("");
for (const p of journal) {
  out.push(
    `insert into journal (id,title,slug,excerpt,body,tags,seo,published_at) values (${q(p.id)},${q(p.title)},${q(p.slug)},${q(p.excerpt)},${q(p.body)},${arr(p.tags)},${j(p.seo)},${q(p.publishedAt)}) on conflict (id) do nothing;`,
  );
}
out.push("");

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "supabase", "seed.sql");
writeFileSync(target, out.join("\n"), "utf8");
console.log(`Wrote ${target} (${categories.length} categories, ${qualities.length} qualities, ${collections.length} collections, ${designs.length} designs, ${journal.length} articles)`);
